Add PHP 8 attributes support
paysera/lib-api-bundle pull request #15
Opened 2024-04-19 11:45 UTC by fiveight00

2024-05-29 13:31 UTC, matasarei approved these changes

2024-06-05 11:17 UTC, borilyordanov requested changes

2024-06-05 11:17 UTC, borilyordanov commented on src/Service/RoutingLoader/RoutingAttributeLoader.php
> +        object $annot
It appears that PHP 7.2 [introduces the `object` type-hint](https://www.php.net/releases/7_2_0.php).

2024-06-05 14:34 UTC, borilyordanov commented on src/Service/RoutingLoader/RoutingAttributeLoader.php
> +    private const ATTRIBUTE_SUPPORT_PHP_VERSION_ID = 80100; // `new` in initializers support is required
Why do we really need PHP 8.1 and not 8.0?

2024-09-11 10:10 UTC, merged